name: marvel_test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^7.6.0
  card_swiper: ^2.0.4
  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  dio: ^5.2.1+1
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.8.4
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  freezed: ^2.3.5
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1
  pretty_dio_logger: ^1.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - keys.env

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true